### ISSUE TITLE
error after installing AWS-S3 plugin

### ISSUE THREAD

**Issue by momolog** [owen2345/camaleon-cms#189]
Using camaleon 1.0.7.

1) downloaded Media AWS S3 plugin and copied it to 'app/apps/plugins'
2) activated plugin in the backend 
3) ran bundle install (because gems were missing)
4) ran into the following error:

```
% rails s
=> Booting WEBrick
=> Rails 4.2.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/camaleon_cms-1.0.7/config/routes/admin.rb:118:in `eval': 'plugins/camaleon-media_aws_s3-master/admin' is not a supported controller name. This can lead to potential routing problems. See http://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use (ArgumentError)
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:319:in `translate_controller'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:256:in `block in check_controller_and_action'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:271:in `check_part'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:255:in `check_controller_and_action'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:178:in `normalize_options!'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:100:in `initialize'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:78:in `new'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:78:in `build'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1559:in `add_route'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1536:in `decomposed_match'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1517:in `block in match'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1507:in `each'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1507:in `match'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:689:in `map_method'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:650:in `get'
	from (eval):4:in `block (4 levels) in <top (required)>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:881:in `block in namespace'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:816:in `scope'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:881:in `namespace'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1455:in `namespace'
	from (eval):3:in `block (3 levels) in <top (required)>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:881:in `block in namespace'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:816:in `scope'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:881:in `namespace'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1455:in `namespace'
	from (eval):2:in `block (2 levels) in <top (required)>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:816:in `scope'
	from (eval):1:in `block in <top (required)>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/camaleon_cms-1.0.7/config/routes/admin.rb:118:in `eval'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/camaleon_cms-1.0.7/config/routes/admin.rb:118:in `block in <top (required)>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:434:in `instance_exec'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:412:in `draw'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/camaleon_cms-1.0.7/config/routes/admin.rb:1:in `<top (required)>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `call'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/aljoscha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/aljoscha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/aljoscha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/aljoscha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/aljoscha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/aljoscha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/aljoscha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/aljoscha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/aljoscha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
	from /Users/aljoscha/rails/avs-berlin/config/environment.rb:5:in `<top (required)>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/aljoscha/rails/avs-berlin/config.ru:3:in `block in <main>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /Users/aljoscha/rails/avs-berlin/config.ru:in `new'
	from /Users/aljoscha/rails/avs-berlin/config.ru:in `<main>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/server.rb:61:in `app'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/server.rb:78:in `start'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/aljoscha/rails/avs-berlin/bin/rails:8:in `require'
	from /Users/aljoscha/rails/avs-berlin/bin/rails:8:in `<top (required)>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/client/rails.rb:28:in `load'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/client/rails.rb:28:in `call'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/client/command.rb:7:in `call'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/client.rb:28:in `run'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/bin/spring:49:in `<top (required)>'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `load'
	from /Users/aljoscha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/aljoscha/rails/avs-berlin/bin/spring:13:in `require'
	from /Users/aljoscha/rails/avs-berlin/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

Anything I am missing?

**Comment by raulanatol** [comment]
Hi @momolog!

Try to change the name of the plugin folder.
Current = camaleon-media_aws_s3-master
Try with = **media_aws_s3**

I'm sorry for the inconvenience.
We be planning remove this plugin to use on native camaleon_cms without plugins.
Please follow this issue to more information: https://github.com/owen2345/camaleon-cms/issues/107

Regards!

**Comment by momolog** [comment]
@raulanatol Ah, exactly, that makes it work! Thanks. 

There should be some sort of README somewhere, clearing this up. Also there are a couple of extra questions that this could probably answer:
1) why is the main navigation empty when inside the plugin settings (probably a bug?)
2) What does CDN Base path URL mean and how should I use it? and
3) does the plugin introduce a dependency to Redis (because I am getting this error in the log):
```
NameError (uninitialized constant Plugins::MediaAwsS3::Models::CacheConnector::Redis):
  app/apps/plugins/media_aws_s3/models/cache_connector.rb:4:in `initialize'
  app/apps/plugins/media_aws_s3/admin_controller.rb:46:in `new'
  app/apps/plugins/media_aws_s3/admin_controller.rb:46:in `elfinder'
```

![dashboard](https://cloud.githubusercontent.com/assets/71108/10860210/ba8752ea-7f65-11e5-84f8-fbf94b21acfa.jpg)

**Comment by raulanatol** [comment]
Hi @momolog 

Thanks for your feedback.
Now I'm working to make aws s3 native in camaleon_cms. For this reason I have not upgraded this plugin.
In a few days I will do it.
Sorry for the inconvenience.

Regards.

**Comment by momolog** [comment]
@raulanatol Thanks for the explanation.
Is there any time frame for making S3 uploads native? 
And isn't this necessary for being able to host Camaleon CMS on heroku or are there other options?

**Comment by owen2345** [comment]
hey @momolog 
you can try the new version 2.0 here:
https://github.com/owen2345/camaleon-cms/tree/moduler
It supports natively s3 and many improvements.
I am waiting for a free time to update the documentations and videos for this new version.

**Comment by yortz** [comment]
I am actually trying to set up S3 credentials in moduler branch but it looks like the settings don't get saved, got no warning or errors, just it looks like that when clicking on "submit" button nothing happens, I am wondering if anyone else is expereincing this same kind of issue or if I need to open a new issue for this.

**Comment by momolog** [comment]
S3 support in moduler branch works

**Comment by owen2345** [comment]
great!

**Comment by yortz** [comment]
I can confirm that S3 is working on S3 after latest merge of the fix i've released for the missing s3 endpoint. We can consider this closed as stated by @owen2345 at least if future pushes don't break this part :smile:
