### ISSUE TITLE
no implicit conversion of Time into String

### ISSUE THREAD

**Issue by guillaumechaumet** [owen2345/camaleon-cms#237]
```   
 def parse(date, now=self.now)
      comp = !block_given?
      d = Date._parse(date, comp)
      year = d[:year]
      year = yield(year) if year && !comp
      make_time(date, year, d[:mon], d[:mday], d[:hour], d[:min], d[:sec], d[:sec_fraction], d[:zone], now)
```
The following link seems to propose a solution: http://stackoverflow.com/questions/20356609/ruby-no-implicit-conversion-of-fixnum-into-string-typeerror

**Comment by yortz** [comment]
This actually happens to me as well after pulling in latest changes from `moduler` branch, looks like if i restart the app by touching `tmp/restart.txt` everything seems to work again ?????

**Comment by guillaumechaumet** [comment]
it works! 
thanks

**Comment by yortz** [comment]
@guillaumechaumet yup even tough that is totally weird, and actually this is a quick fix only if you are running on passenger with apache as I am doing; honestly I think that this definitively needs further investigation, since this way it's not production ready yet :cry:

**Comment by owen2345** [comment]
Please send me a screenshot where appears this error.

**Comment by yortz** [comment]
Hi this actually appears everywhere in the main app (FE and admin) I've actually downgraded camaleon and i got rid of latest changes, since I am actually on a tight schedule; I'll see if I'll have some spare time to document better this kind of issue next week, but you can also ask @guillaumechaumet that was the last one experiencing this kind of weird behaviour. Thanks for your support on this.

**Comment by momolog** [comment]
`touch tmp/restart.txt` only temporarily fixes the problem. It comes back.
Backtrace:
```
TypeError (no implicit conversion of Time into String):
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/apps/plugins/attack/attack_helper.rb:63:in `attack_check_request'
   vendor/ruby-2.0.0/lib/ruby/2.0.0/time.rb:325:in `_parse'
   vendor/ruby-2.0.0/lib/ruby/2.0.0/time.rb:325:in `parse'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/apps/plugins/attack/attack_helper.rb:53:in `attack_app_before_load'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:47:in `rescue in block in _do_hook'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:39:in `_do_hook'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/controllers/camaleon_cms/frontend_controller.rb:229:in `before_hooks'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:24:in `hooks_run'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:41:in `block in _do_hook'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:39:in `each'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:25:in `block in hooks_run'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:24:in `each'
   vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:164:in `call'
```

**Comment by owen2345** [comment]
Fixed!
