### ISSUE TITLE
Unable to run migrations

### ISSUE THREAD

**Issue by atbyrd** [owen2345/camaleon-cms#24]
When running the initial migration it fails because there is no definition for the sites table.
```
== 20150611161134 PostTableIntoUtf8: migrating ================================
-- create_table("users")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "sites" does not exist
: ALTER TABLE "users" ADD CONSTRAINT "fk_rails_1901bc9cf9"
FOREIGN KEY ("site_id")
  REFERENCES "sites" ("id")
/Users/atbyrd/dev/camaleon-cms/db/migrate/20150611161134_post_table_into_utf8.rb:3:in `change'
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "sites" does not exist
: ALTER TABLE "users" ADD CONSTRAINT "fk_rails_1901bc9cf9"
FOREIGN KEY ("site_id")
  REFERENCES "sites" ("id")
/Users/atbyrd/dev/camaleon-cms/db/migrate/20150611161134_post_table_into_utf8.rb:3:in `change'
PG::UndefinedTable: ERROR:  relation "sites" does not exist
/Users/atbyrd/dev/camaleon-cms/db/migrate/20150611161134_post_table_into_utf8.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by owen2345** [comment]
Thank you for the report, I am working in the fix...

**Comment by owen2345** [comment]
Fixed!

**Comment by atbyrd** [comment]
@owen2345 Thanks
