### ISSUE TITLE
TypeError (no implicit conversion of Time into String)

### ISSUE THREAD

**Issue by momolog** [owen2345/camaleon-cms#243]
Using camaleon_cms (2.0.2 / beb71a890702805ee934207acbe2f004f0e17fa2)

I am getting this exception in my live deploy on a regular basis without any specific reason:

```
TypeError (no implicit conversion of Time into String):
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/apps/plugins/attack/attack_helper.rb:63:in `attack_check_request'
   vendor/ruby-2.0.0/lib/ruby/2.0.0/time.rb:325:in `_parse'
   vendor/ruby-2.0.0/lib/ruby/2.0.0/time.rb:325:in `parse'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/apps/plugins/attack/attack_helper.rb:53:in `attack_app_before_load'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:47:in `rescue in block in _do_hook'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:39:in `_do_hook'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/controllers/camaleon_cms/frontend_controller.rb:229:in `before_hooks'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:24:in `hooks_run'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:41:in `block in _do_hook'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:39:in `each'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:25:in `block in hooks_run'
   vendor/bundle/ruby/2.0.0/bundler/gems/camaleon-cms-beb71a890702/app/helpers/camaleon_cms/hooks_helper.rb:24:in `each'
   vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:164:in `call'
```

This breaks the site badly.

**Comment by guillaumechaumet** [comment]
see this: 
https://github.com/owen2345/camaleon-cms/issues/237

**Comment by momolog** [comment]
Duplicate of #237.

**Comment by owen2345** [comment]
Fixed!
