### ISSUE TITLE
undefined method `get_taxonomy' error 

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#341]
Hi,

I am getting undefined method `get_taxonomy' error if I use "Wordpress" theme. Here is the exception details.
````
                </span>
                <span class="categories-links">
                    <%= raw get_taxonomy(post.the_categories.decorate, 'category tag') %>
                </span>
                <span class="tags-links">
                    <%= raw get_taxonomy(post.the_tags.decorate, 'tag') %>


/Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-cms-bdd794494cef/app/apps/themes/default/views/index.html.erb:17:in `block in ___sers_mazharoddin__rvm_gems_ruby_______rails______bundler_gems_camaleon_cms_bdd______cef_app_apps_themes_default_views_index_html_erb___3739040920932999278_70329040094240'
draper (1.4.0) lib/draper/delegation.rb:10:in `each'
draper (1.4.0) lib/draper/delegation.rb:10:in `each_with_index'
draper (1.4.0) lib/draper/delegation.rb:10:in `each_with_index'
/Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-cms-bdd794494cef/app/apps/themes/default/views/index.html.erb:1:in `___sers_mazharoddin__rvm_gems_ruby_______rails______bundler_gems_camaleon_cms_bdd______cef_app_apps_themes_default_views_index_html_erb___3739040920932999278_70329040094240'
actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
````

**Comment by owen2345** [comment]
@mazharoddin 
Please try restarting your server, because the method is present here:
https://github.com/owen2345/camaleon-cms/blob/master/app/apps/themes/default/default_helper.rb

**Comment by mazharoddin** [comment]
Thanks @owen2345 ..
