### ISSUE TITLE
Error - Reorder custom fields groups

### ISSUE THREAD

**Issue by flaranda** [owen2345/camaleon-cms#36]
Hi,

I found the following error when trying to reorder custom fields groups through the admin panel:

```
Started POST "/admin/api/reorder?model=field_groups" for ::1 at 2015-08-21 13:22:10 +0200

AbstractController::ActionNotFound (The action 'api' could not be found for AdminController):
  actionpack (4.2.3) lib/abstract_controller/base.rb:132:in `process'
  actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `call'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
```

**Comment by owen2345** [comment]
Fixed!
