### ISSUE TITLE
An unhandled lowlevel error occurred while uploading a photo for a user profile.

### ISSUE THREAD

**Issue by gcrofils** [owen2345/camaleon-cms#373]
Giving this avatar : 

![feuille](https://cloud.githubusercontent.com/assets/93443/14164481/96ff23c6-f732-11e5-92ce-4feb1cc37c4e.png)

When I try to upload it as a new photo, it fails.

![capture d ecran 2016-03-31 a 11 29 51](https://cloud.githubusercontent.com/assets/93443/14164668/f7400876-f733-11e5-9f77-cee7b097d1db.png)

[See the screen capture video for more details](https://sendvid.com/qaz453xp).

logs say : 

```
2016-03-31 03:22:19 +0000: Rack app error: #<EOFError: bad content body>
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/multipart/parser.rb:97:in `block in fast_forward_to_first_boundary'
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/multipart/parser.rb:95:in `loop'
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/multipart/parser.rb:95:in `fast_forward_to_first_boundary'
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/multipart/parser.rb:53:in `parse'
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/multipart.rb:25:in `parse_multipart'
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/request.rb:375:in `parse_multipart'
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/request.rb:207:in `POST'
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:39:in `method_override_param'
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:27:in `method_override'
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:15:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/configuration.rb:227:in `call'
/staging/shared/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/server.rb:561:in `handle_request'
/staging/shared/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/server.rb:406:in `process_client'
/staging/shared/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/server.rb:271:in `block in run'
/staging/shared/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/thread_pool.rb:111:in `block in spawn_thread'
```

The same image can be uploaded via Media, and then selected and cropped.

**Comment by owen2345** [comment]
Ufff!!! it is strange, because I did the same with the image in my local and it works well.
http://demo-611.tuzitio.com/admin/media
admin
admin

**Comment by gcrofils** [comment]
It doesn't work for me on your demo.
![capture d ecran 2016-04-11 a 12 03 09](https://cloud.githubusercontent.com/assets/93443/14416573/30c13aa4-ffde-11e5-8c28-1e5b992c9983.png)

[See the video for more details.](http://sendvid.com/j8vuutob)

Can you check the logs ? Around 12:02 pm (GMT+8)

On my side, I tried on our staging server (puma) and on several dev desktops (WEBrick). Same issue.

**Comment by owen2345** [comment]
Fixed!  it was a problem for duplicated library in that section.
