### ISSUE TITLE
install with rails 5.0

### ISSUE THREAD

**Issue by lica667** [owen2345/camaleon-cms#424]
Hello. I started using camaleon with rails 5.0
But at the installation I've already had a trouble.
First, this part
```
require './lib/plugin_routes' 
instance_eval(PluginRoutes.draw_gems)
```
is not working. I founded it when I realized that no gem of Gemfile_camaleon didn't install.

Second. I added code from Gemfile_camaleon into Gemfile and tried `bundle`
As the result, had this error:

```
Bundler could not find compatible versions for gem "rack":
  In snapshot (Gemfile.lock):
    rack (= 2.0.1)

  In Gemfile:
    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      railties (= 5.0.0) was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0) was resolved to 5.0.0, which depends on
          rack (~> 2.0)

    mobu was resolved to 0.0.2, which depends on
      rack (~> 1.4)

    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      railties (= 5.0.0) was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0) was resolved to 5.0.0, which depends on
          rack-test (~> 0.6.3) was resolved to 0.6.3, which depends on
            rack (>= 1.0)

    sass-rails (~> 5.0) was resolved to 5.0.5, which depends on
      sprockets (< 4.0, >= 2.8) was resolved to 3.6.3, which depends on
        rack (< 3, > 1)

```
Could you help me with right installation without any errors at the beginning?

**Comment by yuri-zubov** [comment]
+1

**Comment by owen2345** [comment]
Sorry, Current version was built for rails 4, but I will modify to support rails 5

**Comment by alexbrinkman** [comment]
+1

**Comment by owen2345** [comment]
This month I will solve the problem, some dependency gems are not supported by rails 5 and I will need to replace by other o remove to add manually.
Thanks for your interest in Camaleon CMS.
Regards,

**Comment by alexbrinkman** [comment]
That would be wonderful, thanks.

**Comment by owen2345** [comment]
Rails 5 support added, waiting for issues to fix and publish a new gem version.

**Comment by ChrisFernandez** [comment]
I think im having a similar issue I mean not similar but related.. at first I had the issue of the people above.. I did a git clone again today and now I get this:
```
rails generate camaleon_cms:install
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /home/rek2/.rvm/gems/ruby-2.3.1/bundler/gems/camaleon-cms-6647029d7e21/lib/camaleon_cms/engine.rb:5)
/home/rek2/.rvm/gems/ruby-2.3.1/gems/breadcrumbs_on_rails-2.3.1/lib/breadcrumbs_on_rails/action_controller.rb:16:in `block in <module:ActionController>': undefined method `helper' for ActionController::API:Class (NoMethodError)
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/concern.rb:120:in `class_eval'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/concern.rb:120:in `append_features'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/breadcrumbs_on_rails-2.3.1/lib/breadcrumbs_on_rails/railtie.rb:14:in `include'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/breadcrumbs_on_rails-2.3.1/lib/breadcrumbs_on_rails/railtie.rb:14:in `block (2 levels) in <class:Railtie>'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_controller/api.rb:145:in `<class:API>'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_controller/api.rb:88:in `<module:ActionController>'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_controller/api.rb:5:in `<top (required)>'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/jbuilder-2.6.0/lib/jbuilder/railtie.rb:20:in `block (2 levels) in <class:Railtie>'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/jbuilder-2.6.0/lib/jbuilder/railtie.rb:19:in `block in <class:Railtie>'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/rek2/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /home/rek2/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/rek2/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'rek2@anarchohacker:~/hackernol$ 
        from /home/rek2/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/rek2/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /home/rek2/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /home/rek2/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/rek2/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /home/rek2/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
        from /home/rek2/hackernol/config/environment.rb:5:in `<top (required)>'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:92:in `preload'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
        from /home/rek2/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/rek2/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/rek2/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

**Comment by owen2345** [comment]
Hey @ChrisFernandez 
could you please try this?
* locate the gem 'breadcrumbs_on_rails' directory
```
bundle show breadcrumbs_on_rails
```

* within the gem dir, search a file
```
lib/breadcrumbs_on_rails/railtie.rb
```
* change the content like this
https://github.com/weppos/breadcrumbs_on_rails/pull/77/files

Note: the error is with "breadcrumbs_on_rails" gem to support rails 5
I tried to reproduce the error, but in my machine works well

**Comment by killinit** [comment]
Hello owen2345
When rails 5 will be released?

**Comment by owen2345** [comment]
Done, please read readme for extra settings in rails 5.
