### ISSUE TITLE
Direction should be :asc or :desc

### ISSUE THREAD

**Issue by bianca** [owen2345/camaleon-cms#425]
Right after installation, i get the following error:

`Direction should be :asc or :desc`

Pertinent details:
- Camaleon-cms version 2.2.0, Rails version 4.1.6
- installed over an existing app
- the only configuration I've done is change "relative_root_url" to equal "blog"

Any suggestions?

**Comment by owen2345** [comment]
Hi @bianca 
could you please send me more details about it? maybe the full error message of your console

**Comment by jamieshiz** [comment]
I am having this issue as well. Here are my environment details

- fresh install
- ruby-2.3.0
- camaleon_cms 2.3.6
- uncommented "gem 'bcrypt-ruby', '~> 3.0.0’ " from Gemfile to resolve setup error
```
Started GET "/" for 127.0.0.1 at 2016-10-26 07:21:28 -0700
Processing by CamaleonCms::FrontendController#index as HTML
  Parameters: {"locale"=>""}
  CamaleonCms::Site Load (0.2ms)  SELECT "cama_term_taxonomy".* FROM "cama_term_taxonomy" WHERE "cama_term_taxonomy"."taxonomy" = 'site' AND "cama_term_taxonomy"."slug" IN ('localhost:3000') ORDER BY "cama_term_taxonomy"."term_group" DESC LIMIT 1
============================ Please define the $current_site = CamaleonCms::Site.first.decorate
Completed 500 Internal Server Error in 10ms

ArgumentError (Direction should be :asc or :desc):
  activerecord (4.0.0) lib/active_record/relation/query_methods.rb:1017:in `block in validate_order_args'
  activerecord (4.0.0) lib/active_record/relation/query_methods.rb:1015:in `each'
  activerecord (4.0.0) lib/active_record/relation/query_methods.rb:1015:in `validate_order_args'
  activerecord (4.0.0) lib/active_record/relation/query_methods.rb:312:in `reorder!'
  activerecord (4.0.0) lib/active_record/relation/query_methods.rb:307:in `reorder'
  activerecord (4.0.0) lib/active_record/querying.rb:9:in `reorder'
  camaleon_cms (2.3.6) app/models/camaleon_cms/site.rb:116:in `main_site'
  camaleon_cms (2.3.6) app/controllers/camaleon_cms/camaleon_controller.rb:94:in `cama_site_check_existence'
  activesupport (4.0.0) lib/active_support/callbacks.rb:407:in `_run__389282843896577891__process_action__callbacks'
  activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.0) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.0) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.0) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.0) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  activerecord (4.0.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.0.0) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.0) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.0.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.0.0) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:80:in `call'
  actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:48:in `call'
  actionpack (4.0.0) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:655:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  activerecord (4.0.0) lib/active_record/migration.rb:369:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.0) lib/active_support/callbacks.rb:373:in `_run__3077245574748006414__call__callbacks'
  activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/reloader.rb:64:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.0) lib/rails/rack/logger.rb:21:in `block in call'
  activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `block in tagged'
  activesupport (4.0.0) lib/active_support/tagged_logging.rb:25:in `tagged'
  activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `tagged'
  railties (4.0.0) lib/rails/rack/logger.rb:21:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.0) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call'
  railties (4.0.0) lib/rails/engine.rb:511:in `call'
  railties (4.0.0) lib/rails/application.rb:97:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
  /Users/jamieschiesel/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
  /Users/jamieschiesel/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
  /Users/jamieschiesel/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```
