### ISSUE TITLE
Error with theme generator

### ISSUE THREAD

**Issue by mukkoo** [owen2345/camaleon-cms#43]
running 
```
$ rails g ctheme my_theme_name
```
the result is 
```
/Users/my_user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:1386:in `copy': unknown file type: /application_path/lib/generators/ctheme_template/app (RuntimeError)
  from /Users/my_user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:471:in `block in copy_entry'
  from /Users/my_user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:1497:in `call'
  from /Users/my_user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:1497:in `wrap_traverse'
  from /Users/my_user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:468:in `copy_entry'
  from /Users/my_user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:443:in `block in cp_r'
  from /Users/my_user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
  from /Users/my_user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
  from /Users/my_user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
  from /Users/my_user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:442:in `cp_r'
  from /Users/my_user/Development/camaleon-cms/lib/generators/ctheme_generator.rb:26:in `create_initializer_file'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/railties-4.2.4/lib/rails/generators.rb:157:in `invoke'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/railties-4.2.4/lib/rails/commands/generate.rb:13:in `<top (required)>'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:50:in `generate'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /Users/my_user/.rvm/gems/ruby-2.2.3@gemset_name/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
  from ./bin/rails:4:in `require'
  from ./bin/rails:4:in `<main>'
```

I'm using RVM with ruby 2.2.3.
I've replaced the my application path with 'application_path' in the output above.

**Comment by owen2345** [comment]
Fixed!
Don't forget to do:
bundle update
Regards,

**Comment by mukkoo** [comment]
It works.
Thanks a lot!
