### ISSUE TITLE
Camaleon doesn't run in both  rails 4.2.7 and with rails 5 ?

### ISSUE THREAD

**Issue by prdpspkt** [owen2345/camaleon-cms#443]
**In rails 5**
The problem is with breadcrumb_on_rails. Problem not solved.

**In rails 4.2.7**
/home/pradeep/adexchange/config/environments/development.rb:53:in `block in <top (required)>': uninitialized constant ActiveSupport::EventedFileUpdateChecker (NameError)
	from /home/pradeep/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/railtie.rb:210:in `instance_eval'
	from /home/pradeep/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/railtie.rb:210:in `configure'
	from /home/pradeep/adexchange/config/environments/development.rb:1:in `<top (required)>'
	from /home/pradeep/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'

**Please help**

**Comment by prdpspkt** [comment]
It was due to breadcrumb_on_rails gem. I solved it.
