### ISSUE TITLE
Custom PaymentMethod Error 

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#454]
Hi @owen2345,
I am getting custom PaymentMethod error while trying add payment methods in '1.1' version of ecommerce plugin.
````
 Showing /Users/mazhar/.rvm/gems/ruby-2.3.0@rails4.2.7/bundler/gems/camaleon-ecommerce-d355cda8abc6/app/views/plugins/ecommerce/admin/payment_methods/form.html.erb where line #35 raised:

undefined local variable or method `args' for #<Plugins::Ecommerce::Admin::PaymentMethodsController:0x007fc5e3d5f038>
````
      # }
    }.call
    args[:custom_payment_methods]
  end

end

```
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails4.2.7/bundler/gems/camaleon-ecommerce-d355cda8abc6/app/helpers/plugins/ecommerce/ecommerce_functions_helper.rb:66:in `ecommerce_custom_payment_methods'
actionpack (4.2.7) lib/abstract_controller/helpers.rb:67:in `ecommerce_custom_payment_methods'
```

Due to this error I am unable to add any payment methods.

**Comment by owen2345** [comment]
Fixed!
Typing error.
