### ISSUE TITLE
ForbiddenAttributesError  in ShippingMethodsController

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#455]
Hi @owen2345 ,

I am getting below error while trying to add shipping methods with ecommerce version 1.1.
```
      def sanitize_for_mass_assignment(attributes)
        if attributes.respond_to?(:permitted?) && !attributes.permitted?
          raise ActiveModel::ForbiddenAttributesError
        else
          attributes
        end

activemodel (4.2.7) lib/active_model/forbidden_attributes_protection.rb:21:in `sanitize_for_mass_assignment'
activerecord (4.2.7) lib/active_record/attribute_assignment.rb:33:in `assign_attributes'
activerecord (4.2.7) lib/active_record/core.rb:566:in `init_attributes'
---
--
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails4.2.7/bundler/gems/camaleon-ecommerce-d355cda8abc6/app/controllers/plugins/ecommerce/admin/shipping_methods_controller.rb:33:in `create'
```
Due to this error unable to add any shipping methods.

**Comment by owen2345** [comment]
done!
strong parameters problem.
