### ISSUE TITLE
undefined method `id' for nil:NilClass while trying to access ecommerce posts as un logged in user.

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#472]
Hi @owen2345,
I am getting below error while trying access product post as non-logged in user, due to this error unable to access any post as un-authenticated user.
```
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/gems/camaleon_cms-2.3.3/app/views/camaleon_cms/default_theme/single.html.erb where line #35 raised
undefined method `id' for nil:NilClass
 <div class="purchase">
                <% if @post.in_stock? %>
                    <% if @post.the_qty_real.to_i > 0 %>
                        <%= form_tag(plugins_ecommerce_checkout_cart_add_path, :method => "post", :class => "form") do %>
                            <div class="input-group">
                                <span class="input-group-addon">Qty: </span>
app/apps/themes/e_shop/views/post_types/commerce/single.html.erb:35:in `_app_apps_themes_e_shop_views_post_types_commerce_single_html_erb___495668316426832872_70198053051100'
```
This error is happening with other themes aswell.

with default theme(camaleon_first).
```
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/gems/camaleon_cms-2.3.3/app/views/camaleon_cms/default_theme/single.html.erb where line #42 raised:
undefined method `id' for nil:NilClass
 # return the total of products available to sell
  def the_qty_real(variation_id = nil)
    carts = h.current_site.carts.where.not(user_id: h.current_user.id).active_cart.joins(:product_items)
    if variation_id.present?
      (get_variation(variation_id).qty || 0) - carts.where("#{Plugins::Ecommerce::ProductItemDecorator.table_name}" => {variation_id: variation_id}).sum("#{Plugins::Ecommerce::ProductItem.table_name}.qty")
    else
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/bundler/gems/camaleon-ecommerce-9078f600ed2c/app/decorators/plugins/ecommerce/product_decorator.rb:107:in `the_qty_real'
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/bundler/gems/camaleon-ecommerce-9078f600ed2c/app/decorators/plugins/ecommerce/product_decorator.rb:86:in `the_stock_status'
/Users/mazhar/.rvm/gems/ruby-2.3.0@rails5.0.0/bundler/gems/camaleon-ecommerce-9078f600ed2c/app/views/post_types/commerce/single.html.erb:42:in 
```
Due to this error unable to access any products without logging in.

**Comment by p-decoraid** [comment]
I have some work-in-progress code in https://github.com/owen2345/camaleon-ecommerce/pull/40 that may fix this.

**Comment by mazharoddin** [comment]
Ok, Thanks.

**Comment by p-decoraid** [comment]
+bug fix in https://github.com/owen2345/camaleon-ecommerce/pull/41

**Comment by mazharoddin** [comment]
Its working now, thanks @p-decoraid.
