### ISSUE TITLE
rails generate camaleon_cms:install fails

### ISSUE THREAD

**Issue by ozgun** [owen2345/camaleon-cms#55]
Forgot to add backtrace in previous message, sorry about that.

```
/home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec': Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:50:in `establish_connection'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activerecord-4.2.4/lib/active_record/railtie.rb:120:in `block (2 levels) in <class:Railtie>'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `each'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activerecord-4.2.4/lib/active_record/base.rb:315:in `<module:ActiveRecord>'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activerecord-4.2.4/lib/active_record/base.rb:26:in `<top (required)>'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/camaleon_cms-0.2.1/config/initializers/active_record_extension.rb:32:in `<top (required)>'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:411:in `call'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `call'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
        from /home/ozgun/Workspace/cms_cameleon_project/config/environment.rb:5:in `<top (required)>'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/spring-1.3.6/lib/spring/application.rb:92:in `require'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/spring-1.3.6/lib/spring/application.rb:92:in `preload'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
        from /home/ozgun/.rvm/gems/ruby-2.1.1@camaleon_cms/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ozgun/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'

```

Gemfile is:

```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'camaleon_cms'
```

**Comment by owen2345** [comment]
I found a fix:
change in your Gemfile
# gem 'mysql2'
gem 'mysql2', '~> 0.3.13'

**Comment by ozgun** [comment]
Thanks, that fixed it.
