### ISSUE TITLE
AJAX calls and media queries uses http on https site

### ISSUE THREAD

**Issue by alvingarcia** [owen2345/camaleon-cms#735]
I installed camaleon-cms to an existing app running on https.

My problem is the admin uses `http` on AJAX calls and media queries. The requests are being blocked because it's using `http`.
(eg. http://ww.existing-app.com/cms-admin/ajax?mode=save_intro)

Is this a bug? or does it need a config or something?

**Comment by owen2345** [comment]
Hi @alvingarcia I tested and it works well, check my tested screenshots:
<img width="1038" alt="2017-11-23_1534" src="https://user-images.githubusercontent.com/1148415/33186954-5d247c0c-d064-11e7-8930-7de720b351af.png">
<img width="830" alt="2017-11-23_1532" src="https://user-images.githubusercontent.com/1148415/33186955-5d7b1666-d064-11e7-88be-9f937ea308ab.png">

**Comment by alvingarcia** [comment]
Hi @owen2345 
It's behaving differently on the site. please check my screenshots:
![image](https://user-images.githubusercontent.com/978771/33197476-8dee2bd2-d120-11e7-9f43-f9363efc7978.png)

The second AJAX call uses https but didn't save my `save_intro` response.

![image](https://user-images.githubusercontent.com/978771/33197493-abc65e86-d120-11e7-8203-95bacb3861a9.png)


There's also a login popup when I'm updating the favicon. After I submit my admin credentials, it redirects me to `/admin/login` page with all-white display. When I checked the logs:

```ruby
Started POST "/admin/login" for 112.207.174.161 at 2017-11-24 16:43:28 +1100
Processing by CamaleonCms::Admin::SessionsController#login_post as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Ax39KHiIEW5Z99Q47Veb/lqsYigLXwvxCEnEA6XDnAm165El9rb5p5sm1W2VoPS3TPVn0Zj57YrHpSjYWgugAA==", "user"=>{"username"=>"admin", "password"=>"[FILTERED]"}, "remember_me"=>"on"}
  CamaleonCms::Site Load (2.2ms)  SELECT  "cms_term_taxonomy".* FROM "cms_term_taxonomy" WHERE "cms_term_taxonomy"."taxonomy" = $1 ORDER BY "cms_term_taxonomy"."term_group" DESC LIMIT $2  [["taxonomy", "site"], ["LIMIT", 1]]
  CamaleonCms::User Load (0.8ms)  SELECT  "cms_users".* FROM "cms_users" WHERE "cms_users"."site_id" = $1 AND "cms_users"."auth_token" = $2 ORDER BY "cms_users"."role" ASC LIMIT $3  [["site_id", 1], ["auth_token", "rz5VjksIULGbLtVFR2mMyg"], ["LIMIT", 1]]
  CamaleonCms::Meta Load (0.8ms)  SELECT  "cms_metas".* FROM "cms_metas" WHERE "cms_metas"."objectid" = $1 AND "cms_metas"."object_class" = $2 AND "cms_metas"."key" = $3 ORDER BY "cms_metas"."id" ASC LIMIT $4  [["objectid", 1], ["object_class", "Site"], ["key", "_default"], ["LIMIT", 1]]
Camaleon CMS - Hook "app_before_load" executed from dependency front_cache
Camaleon CMS - Hook "app_before_load" executed from dependency cama_contact_form
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 9ms (ActiveRecord: 3.8ms)

ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):

actionpack (5.0.6) lib/action_controller/metal/request_forgery_protection.rb:195:in `handle_unverified_request'
actionpack (5.0.6) lib/action_controller/metal/request_forgery_protection.rb:223:in `handle_unverified_request'
actionpack (5.0.6) lib/action_controller/metal/request_forgery_protection.rb:218:in `verify_authenticity_token'
activesupport (5.0.6) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.6) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
actionpack (5.0.6) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
activesupport (5.0.6) lib/active_support/callbacks.rb:170:in `block in halting'
activesupport (5.0.6) lib/active_support/callbacks.rb:454:in `block in call'
activesupport (5.0.6) lib/active_support/callbacks.rb:454:in `each'
activesupport (5.0.6) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.6) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.6) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.6) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
```

BTW, thanks for the quick response!

**Comment by Gloumy** [comment]
Had the same problem, after a bit of research i added this to my nginx configuration inside the / location : 
`proxy_set_header X-Forwarded-Proto $scheme;`

Seems to work now
