### ISSUE TITLE
[Request] Use Travis CI

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon-cms#778]
It took me awhile to get the tests to run. I had to add `require 'pathname'` at the top of spec_helper.rb. I'm not sure how anyone can run the spec without that change.

As noted on Gitter, the first test run fails, while the second one (mostly) succeeds. I still have three tests failing consistently, though. I'd like to know if these tests are specific to my local environment, or if the spec is failing.

Ruby 2.4.2
Rails 5.1.4
Camaleon latest git version
Phantomjs 2.1.1

```
Failures:

  1) PostTypeDecorator group url
     Failure/Error: send(url_to.gsub('-', '_'), *(args << options))

     NoMethodError:
       undefined method `host' for nil:NilClass
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/action_controller/metal/url_for.rb:30:in `url_options'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/routing_url_for.rb:122:in `url_options'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:259:in `call'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:325:in `block (2 levels) in define_url_helper'
     # ./app/helpers/camaleon_cms/frontend/application_helper.rb:34:in `cama_url_to_fixed'

     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/draper-3.0.0/lib/draper/helper_proxy.rb:33:in `block in define_proxy'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/draper-3.0.0/lib/draper/helper_proxy.rb:14:in `method_missing'
     # ./app/decorators/camaleon_cms/post_type_decorator.rb:28:in `the_group_url'
     # ./spec/decorators/post_type_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:189:in `block (3 levels) in <top (required)>'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/base.rb:98:in `cleaning'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/spec_helper.rb:188:in `block (2 levels) in <top (required)>'

  2) PostTypeDecorator public url
     Failure/Error: send(url_to.gsub('-', '_'), *(args << options))

     NoMethodError:
       undefined method `host' for nil:NilClass
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/action_controller/metal/url_for.rb:30:in `url_options'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/routing_url_for.rb:122:in `url_options'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:259:in `call'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:325:in `block (2 levels) in define_url_helper'
     # ./app/helpers/camaleon_cms/frontend/application_helper.rb:34:in `cama_url_to_fixed'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/draper-3.0.0/lib/draper/helper_proxy.rb:33:in `block in define_proxy'
     # ./app/decorators/camaleon_cms/post_type_decorator.rb:15:in `the_url'
     # ./spec/decorators/post_type_spec.rb:11:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:189:in `block (3 levels) in <top (required)>'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/base.rb:98:in `cleaning'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/spec_helper.rb:188:in `block (2 levels) in <top (required)>'

  3) the signin process create edit post
     Failure/Error: send(url_to.gsub('-', '_'), *(args << options))

     NoMethodError:
       undefined method `host' for nil:NilClass
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/action_controller/metal/url_for.rb:30:in `url_options'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/routing_url_for.rb:122:in `url_options'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:259:in `call'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:325:in `block (2 levels) in define_url_helper'
     # ./app/helpers/camaleon_cms/frontend/application_helper.rb:34:in `cama_url_to_fixed'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/draper-3.0.0/lib/draper/helper_proxy.rb:33:in `block in define_proxy'
     # ./app/decorators/camaleon_cms/post_decorator.rb:104:in `the_url'
     # ./app/decorators/camaleon_cms/post_decorator.rb:47:in `the_path'
     # ./spec/support/common.rb:62:in `get_content_attr'
     # ./spec/features/posts_spec.rb:33:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:189:in `block (3 levels) in <top (required)>'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/base.rb:98:in `cleaning'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/briankephart/.rvm/gems/ruby-2.4.2/gems/database_cleaner-1.6.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/spec_helper.rb:188:in `block (2 levels) in <top (required)>'

Finished in 3 minutes 42.4 seconds (files took 3.4 seconds to load)
86 examples, 3 failures

Failed examples:

rspec ./spec/decorators/post_type_spec.rb:4 # PostTypeDecorator group url
rspec ./spec/decorators/post_type_spec.rb:9 # PostTypeDecorator public url
rspec ./spec/features/posts_spec.rb:21 # the signin process create edit post
```

**Comment by brian-kephart** [comment]
I'm still wondering. Does the spec pass on the current version for anyone else?

**Comment by brian-kephart** [comment]
I figured out part of what I was experiencing. The issue with `require 'pathname'` went away when I switched ruby versions. I could not get it to reoccur even when I switched back to the troubled version, so that seems like an isolated case.

I still don't know why the tests are failing though, and I have more of them failing than before, mostly with this error:
```
ArgumentError:
  arguments passed to url_for can't be handled. Please require routes or provide your own implementation
  /Users/briankephart/.rvm/gems/ruby-2.5.1/gems/actionview-5.1.4/lib/action_view/helpers/url_helper.rb:38:in `url_for'
```
It would be helpful to know:
1. if anyone can get the spec to pass currently,
2. what versions of ruby/rails were used when the spec passed.

**Comment by brian-kephart** [comment]
I still haven't ever successfully run the test suite, despite many attempts over a period of months. I believe that my contributions would be better and more reliable if I was able to run the tests. I've changed the name of this issue to request that this repo use [Travis CI](https://travis-ci.com) or some other build system to run tests in a controlled environment.

**Comment by owen2345** [comment]
Hi @brian-kephart 
I am so sorry for it, I tried many times too with the same result, it was working well.
I can not understand why a simple url_for(...) is generating error with: 
```
arguments passed to url_for can't be handled. Please requ...
```
I executed test files one by one and  worked well. Anyway I am still researching to fix the problem...

**Comment by brian-kephart** [comment]
Thanks @owen2345. I'm not complaining, you do fantastic things for this community! I just want my contributions to be better. I know some of my own PRs have had problems since I wasn't able to fully test them.

Please let me know if there's anything I can do to help with this.

**Comment by owen2345** [comment]
Finally solved! 
Check here: https://travis-ci.org/owen2345/camaleon-cms

**Comment by brian-kephart** [comment]
Fantastic! Thanks Owen, this will improve my contributions for sure.

**Comment by brian-kephart** [comment]
Also, I just ran the test suite on my local machine with no errors for the first time ever. Thanks again!
